apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: favourite-service
          image: ${ACR_NAME}.azurecr.io/favourite-service:dev
          ports:
            - containerPort: 8800
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_REGION
              value: "default"
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: "myzone"
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: "http://service-discovery:8761/eureka"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8800
  type: ClusterIP
