apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: alejolonber/payment-service:test
          ports:
            - containerPort: 8400
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_REGION
              value: "default"
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: "myzone"
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: "http://service-discovery:8761/eureka"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: prod
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8400
      targetPort: 8400
  type: ClusterIP
