apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: alejolonber/service-discovery:test
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: prod
spec:
  selector:
    app: service-discovery
  ports:
    - port: 8761
      targetPort: 8761
